# Generated by Django 3.2.8 on 2026-05-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coplete',
            new_name='complete',
        ),
    ]
